function createfigure(X1, YMatrix1, X2, YMatrix2, YMatrix3, YMatrix4)
%CREATEFIGURE(X1,YMATRIX1,X2,YMATRIX2,YMATRIX3,YMATRIX4)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data
%  YMATRIX4:  matrix of y data

%  Auto-generated by MATLAB on 01-Mar-2013 08:22:14
% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1,'YScale','log','YMinorTick','on');
box(subplot1,'on');
hold(subplot1,'all');

% Create multiple lines using matrix input to semilogy
semilogy1 = loglog(X1,YMatrix1,'Parent',subplot1,'LineWidth',2);
set(semilogy1(1),'Color',[1 0 0],'DisplayName','Area dist at T =  5e5');
set(semilogy1(2),'Color',[0 1 0],'DisplayName','Area dist at T =      0');
set(semilogy1(3),'Marker','o','LineStyle','none','Color',[0 0 1],...
    'DisplayName','Pack Area dist',...
    'LineWidth',0.5);

% Create xlabel
xlabel('Diameter');

% Create ylabel
ylabel('Fractional Area');

% Create title
title('Area dist at T =      0 and T =  1e+04','FontSize',16,...
    'FontName','Hoefler Text');

% Create legend
legend(subplot1,'show');

% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1,'YScale','log','YMinorTick','on');
box(subplot2,'on');
hold(subplot2,'all');

% Create multiple lines using matrix input to semilogy

semilogy2 = loglog(X2,YMatrix2,'Parent',subplot2,'LineWidth',2);

set(semilogy2(1),'Color',[0 1 0],'DisplayName','1');
set(semilogy2(2),'LineStyle','--','Color',[0 0 1],...
    'DisplayName','Melting/Advection');
set(semilogy2(3),'LineStyle','-.','Color',[1 0 0],...
    'DisplayName','Redistribution/Advection');
set(semilogy2(4),'LineStyle','-.','Color',[0 1 1],...
    'DisplayName','Swell/Advection');

% Create xlabel
xlabel('Time');

% Create ylabel
ylabel('Ratio of Area Change');

% Create title
title('Relative Area Change over time with respect to advection',...
    'FontSize',16,...
    'FontName','Hoefler Text');

% Create legend
legend(subplot2,'show');

% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1,'YScale','log','YMinorTick','on');
box(subplot3,'on');
hold(subplot3,'all');

% Create multiple lines using matrix input to semilogy
semilogy3 = loglog(X2,YMatrix3,'Parent',subplot3,'LineWidth',2);
set(semilogy3(1),'Color',[0 1 0],'DisplayName','Advection');
set(semilogy3(2),'LineStyle','--','Color',[0 0 1],'DisplayName','Melting');
set(semilogy3(3),'LineStyle','-.','Color',[1 0 0],...
    'DisplayName','Redistribution');
set(semilogy3(4),'LineStyle','-.','Color',[0 1 1],'DisplayName','Swell');

% Create xlabel
xlabel('Time');

% Create ylabel
ylabel({'Area Change',''});

% Create title
title('Total Area change over time','FontSize',16,'FontName','Hoefler Text');

% Create legend
legend(subplot3,'show');

%Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1,'YScale','log','YMinorTick','on');
hold(subplot4,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix4/time,'Parent',subplot4,'LineWidth',2);
set(plot1(1),'LineStyle','--','Color',[0 1 0],...
   'DisplayName','Melting Area Changes');
set(plot1(2),'LineStyle','-.','Color',[0 0 1],'DisplayName','Melting');
set(plot1(3),'LineStyle','-.','Color',[1 0 0],...
   'DisplayName','Redistribution');
set(plot1(4),'LineStyle','--','Color',[0 1 1],'DisplayName','Swell');

% Create xlabel
xlabel({'Diameter',''});

% Create ylabel
ylabel({'Integrated Area Change',''});

% Create title
title('Average Changes in Area per timestep',...
    'FontSize',16,...
    'FontName','Hoefler Text');

% Create legend
legend(subplot4,'show');

