function plotbalance(X1, YMatrix1)
%CREATEFIGURE1(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 12-Mar-2013 12:25:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'XScale','log','XMinorTick','on',...
    'FontSize',16,...
    'FontName','Hoefler Text');
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to semilogx
semilogx1 = semilogx(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(semilogx1(1),'Color',[0 0.498039215803146 0],'DisplayName','Melt');
set(semilogx1(2),'Color',[1 0 0],'DisplayName','Redist');
set(semilogx1(3),'Color',[0 1 0],'DisplayName','Advect');
set(semilogx1(4),'Color',[0 0.749019622802734 0.749019622802734],...
    'DisplayName','Swell');

% Create xlabel
xlabel('Diameter','FontSize',16,'FontName','Hoefler Text');

% Create ylabel
ylabel('\Delta A','FontSize',16,'FontName','Hoefler Text');

% Create title
title({'Balance of Terms at Steady State'},'FontSize',16,...
    'FontName','Hoefler Text');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.721374045801527 0.68409586056645 0.141984732824428 0.203703703703704]);

