function plotFSD(X1, YMatrix1, X2, YMatrix2, YMatrix3, YMatrix4,YMatrix5,time,saveplots)
%CREATEFIGURE(X1,YMATRIX1,X2,YMATRIX2,YMATRIX3,YMATRIX4)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data
%  YMATRIX4:  matrix of y data

%  Auto-generated by MATLAB on 12-Mar-2013 14:16:57

%% This part does the time-varying plotting and other stuff

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1,'YScale','log','YMinorTick','on');
box(subplot1,'on');
hold(subplot1,'all');

% Create multiple lines using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix1,'Parent',subplot1,'LineWidth',2);
set(semilogy1(1),'Color',[1 0 0],'DisplayName',sprintf('T = %d',time));
set(semilogy1(2),'Color',[0 1 0],'DisplayName','T = 0');
set(semilogy1(3),'Marker','o','LineStyle','none','Color',[0 0 1],...
    'DisplayName','Pack',...
    'LineWidth',0.5);

% Create xlabel
xlabel('Diameter');

% Create ylabel
ylabel('Fractional Area');

% Create title
title('A(d)','FontSize',16,...
    'FontName','Hoefler Text');

% Create legend
legend(subplot1,'show');

% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1,'YScale','log','YMinorTick','on');
box(subplot2,'on');
hold(subplot2,'all');

% Create multiple lines using matrix input to semilogy
semilogy2 = semilogy(X2,YMatrix2,'Parent',subplot2,'LineWidth',2);
set(semilogy2(1),'Color',[0 1 0],'DisplayName','1');
set(semilogy2(2),'LineStyle','--','Color',[0 0 1],'DisplayName','Melting');
set(semilogy2(3),'LineStyle','-.','DisplayName','Redist');
set(semilogy2(4),'LineStyle','-.','Color',[0 1 1],'DisplayName','Swell');

% Create xlabel
xlabel('Time');

% Create ylabel
ylabel('Ratio of Area Change');

% Create title
title('Relative Area Change to advection','FontSize',16,...
    'FontName','Hoefler Text');

% Create legend
legend(subplot2,'show');

% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1,'YScale','log','YMinorTick','on');
box(subplot3,'on');
hold(subplot3,'all');

% Create multiple lines using matrix input to semilogy
semilogy3 = semilogy(X2,YMatrix3,'Parent',subplot3,'LineWidth',2);
set(semilogy3(1),'Color',[0 1 0],'DisplayName','Advect');
set(semilogy3(2),'LineStyle','--','Color',[0 0 1],'DisplayName','Melt');
set(semilogy3(3),'LineStyle','-.','DisplayName','Redist');
set(semilogy3(4),'LineStyle','-.','Color',[0 1 1],'DisplayName','Swell');

% Create xlabel
xlabel('Time');

% Create ylabel
ylabel({'Area Change',''});

% Create title
title('Total Area change','FontSize',16,'FontName','Hoefler Text');

% Create legend
legend(subplot3,'show');

% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1,'YScale','log','YMinorTick','on',...
    'XScale','log',...
    'XMinorTick','on');
hold(subplot4,'all');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix4,'Parent',subplot4,'LineWidth',2);
set(loglog1(1),'LineStyle','--','Color',[0 1 0],'DisplayName','Advect');
set(loglog1(2),'LineStyle','-.','Color',[0 0 1],'DisplayName','Melt');
set(loglog1(3),'LineStyle','-.','DisplayName','Redist');
set(loglog1(4),'LineStyle','--','Color',[0 1 1],'DisplayName','Swell');

% Create xlabel
xlabel({'Diameter',''});

% Create ylabel
ylabel({'Integrated Area Change',''});

% Create title
title('Average Change','FontSize',16,'FontName','Hoefler Text');

% Create legend
legend(subplot4,'show');

if saveplots == 1
hgexport(figure1,'Output/Changes.fig')
hgexport(figure1,'Output/Changes.eps')
end

%% Do the Balance Plotting
% Create figure
figure2 = figure;

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure2,'YScale','log','YMinorTick','on',...
    'FontSize',16,...
    'FontName','Hoefler Text');
box(subplot1,'on');
hold(subplot1,'all');


% Create multiple lines using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix1,'Parent',subplot1,'LineWidth',2);
set(semilogy1(1),'Color',[1 0 0],'DisplayName',sprintf('T = %d',time));
set(semilogy1(2),'Color',[0 1 0],'DisplayName','T = 0');
set(semilogy1(3),'Marker','o','LineStyle','none','Color',[0 0 1],...
    'DisplayName','Pack',...
    'LineWidth',0.5);

% Create xlabel
xlabel('Diameter','FontSize',16,'FontName','Hoefler Text');

% Create ylabel
ylabel('Fractional Area','FontSize',16,'FontName','Hoefler Text');

% Create title
title('A(d)','FontSize',16,...
    'FontName','Hoefler Text');

% Create legend
legend(subplot1,'show');

% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure2,'XScale','log','XMinorTick','on',...
    'FontSize',16,...
    'FontName','Hoefler Text');
box(subplot2,'on');
hold(subplot2,'all');

% Create multiple lines using matrix input to semilogx
semilogx1 = semilogx(X1,YMatrix5,'Parent',subplot2,'LineWidth',2);
set(semilogx1(1),'Color',[0 0.498039215803146 0],'DisplayName','Melt');
set(semilogx1(2),'Color',[1 0 0],'DisplayName','Redist');
set(semilogx1(3),'Color',[0 1 0],'DisplayName','Advect');
set(semilogx1(4),'Color',[0 0.749019622802734 0.749019622802734],...
    'DisplayName','Swell');

% Create xlabel
xlabel('Diameter','FontSize',16,'FontName','Hoefler Text');

% Create ylabel
ylabel('\Delta A','FontSize',16,'FontName','Hoefler Text');

% Create title
title({'Steady State Balance'},'FontSize',16,...
    'FontName','Hoefler Text');

% Create legend
legend1 = legend(subplot2,'show');
set(legend1,...
    'Position',[0.754894586518775 0.712786523059929 0.0749436513899324 0.146322378716745]);
if saveplots == 1
hgexport(figure2,'Output/Balances.fig')
hgexport(figure2,'Output/Balances.eps')
end

end